modify validate version job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,7 +6,7 @@ on:
     branches: [master, release/*, develop, feature/*]
 
 jobs:
-  build:
+  Build:
     runs-on: ubuntu-latest
 
     permissions:
@@ -123,7 +123,7 @@ jobs:
                 "as a comment with commit sha on the Pull request. Lints(if any) can also be"\
                 "found as annotations in the Files changed tab on the Pull request" >> $GITHUB_STEP_SUMMARY
 
-  validate-version:
+  Validate-Version:
     if: github.event_name == 'pull_request'
     runs-on: ubuntu-latest
 
@@ -134,30 +134,39 @@ jobs:
           fetch-depth: 0
 
       - name: Check if version is in semantic format
+        id: version_semantic
         run: |
-          import json
-          import os
-          import sys
-          with open("package.json", "r") as f:
-            data = json.load(f)
-            version = data["version"]
-            if len(version.split('.')) != 3 :
-              sys.exit("Version is not in semantic format")
-            
-          env_file = os.getenv("GITHUB_ENV")
-          with open(env_file, "a") as f:
-            f.write(f"VERSION={version}")
+          pip install semantic_version
+          vers=`python3 -c "
+          import semantic_version, configparser
+          read_version = configparser.ConfigParser()
+          read_version.read('VERSION.ini')
+          version = read_version.get('APP', 'version')
+          if semantic_version.validate(version):
+            print(version)
+          else:
+            print('Error: Version not in semantic format')"`
+          if [[ $vers == *"Error"* ]]; then
+            echo $vers
+            exit 1
+          fi
+          echo "Version - "$vers
+          echo "::set-output name=version::$vers"
 
-        shell: python
-
-      - name: Check if version is in CHANGELOG.md
+      - name: Check if version is in ChangeLog file
         run: |
-          import os
-          import sys
-          version = os.getenv("VERSION")
-            
-          with open("CHANGELOG.md", "r") as f:
-            text = f.read()
-          if version not in text:
-            sys.exit("Version is not in CHANGELOG.md")
-        shell: python
+          version=${{ steps.version_semantic.outputs.version }}
+          chgLog=`grep -q "$version" CHANGELOG.md; [ $? -eq 0 ] && echo "Y" || echo "N"`
+          if [[ $chgLog == "N" ]]; then
+            echo "Error: Version not available in CHANGELOG.md file"
+            exit 1
+          fi
+          
+      - name: Check if git tag already exists
+        run: |
+          version=${{ steps.version_semantic.outputs.version }}
+          tag=$(git tag -l "$version")
+          if [ ! -z "$tag" ]; then
+            echo "ERROR: Git tag already exists"
+            exit 1
+          fi
