Update ci.yml with Validate-Version job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,7 +3,7 @@ name: Continuous Integration
 on:
   pull_request:
     types: [opened, synchronize, reopened]
-    branches: [master, release/*, develop, feature/*]
+    branches: [master, release/*, develop]
 
   # workflow_call enables this workflow to be called in another workflow
   workflow_call:
@@ -126,7 +126,7 @@ jobs:
                 "as a comment with commit sha on the Pull request. Lints(if any) can also be"\
                 "found as annotations in the Files changed tab on the Pull request" >> $GITHUB_STEP_SUMMARY
 
-  validate-version:
+  Validate-Version:
     runs-on: ubuntu-latest
 
     steps:
@@ -136,39 +136,72 @@ jobs:
           fetch-depth: 0
 
       - name: Check if version is in semantic format
+        id: version_semantic
         run: |
-          import json
-          import os
-          import sys
-          with open("package.json", "r") as f:
-            data = json.load(f)
-            version = data["version"]
-            if len(version.split('.')) != 3 :
-              sys.exit("Version is not in semantic format")
-            
-          env_file = os.getenv("GITHUB_ENV")
-          with open(env_file, "a") as f:
-            f.write(f"VERSION={version}")
-
-        shell: python
-
-      - name: Check if version is in CHANGELOG.md
+          pip install semantic_version
+          vers=`python3 -c "
+          import semantic_version, configparser
+          read_version = configparser.ConfigParser()
+          read_version.read('VERSION.ini')
+          version = read_version.get('APP', 'version')
+          if semantic_version.validate(version):
+            print(version)
+          else:
+            print('Error: Version not in semantic format')"`
+          if [[ $vers == *"Error"* ]]; then
+            echo $vers
+            exit 1
+          fi
+          echo "Version - "$vers
+          echo "::set-output name=version::$vers"
+          
+      - name: Check if version is in ChangeLog file
         run: |
-          import os
-          import sys
-          version = os.getenv("VERSION")
-            
-          with open("CHANGELOG.md", "r") as f:
-            text = f.read()
-          if version not in text:
-            sys.exit("Version is not in CHANGELOG.md")
-        shell: python
-
+          version=${{ steps.version_semantic.outputs.version }}
+          echo "version is: ${version}"
+          chgLog=`grep -q "$version" CHANGELOG.md; [ $? -eq 0 ] && echo "Y" || echo "N"`
+          if [[ $chgLog == "N" ]]; then
+            echo "Error: Version not available in CHANGELOG.md file"
+            exit 1
+          fi
+          
       - name: Check if git tag already exists
         run: |
-          tag=$(git tag -l "$VERSION")
-          echo "Tag found is $tag"
+          version=${{ steps.version_semantic.outputs.version }}
+          echo "version is: ${version}"
+          tag=$(git tag -l "$version")
           if [ ! -z "$tag" ]; then
-            echo "ERROR: git tag already exists"
+            echo "ERROR: Git tag already exists"
             exit 1
+          fi
+          
+      - name:  Check if tag has the right sequential format
+        run: |
+          baseline='N'
+          if [ ! $(git describe --tags `git rev-list --tags --max-count=1`) &> /dev/null ]; then
+            echo "Error: Git tag need to baselined first"
+            exit 1
+          else
+            baseline='Y'
+            ver=$(git describe --tags `git rev-list --tags --max-count=1`)
+          fi
+          version=${{ steps.version_semantic.outputs.version }}
+          echo "version is: ${version}"
+          if [[ $baseline == 'Y' ]]; then
+          t_current_version=`echo ${version}`
+          echo "t_current_version is: ${t_current_version}"
+          no_sequence=`python3 -c "
+          import semantic_version
+          v = semantic_version.Version('''$ver''')
+          v_major = v.next_major()
+          v_minor = v.next_minor()
+          v_patch = v.next_patch()
+          if('''$t_current_version''' != str(v_major) and '''$t_current_version''' != str(v_minor) and '''$t_current_version''' != str(v_patch)):              
+            print('Y')
+          else:
+            print('N')"`            
+          if [[ $no_sequence != "N" ]]; then
+            echo "Error: Version not in sequential format"
+            exit 1
+          fi
           fi
