check 5

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -69,20 +69,20 @@ jobs:
           version=${{ steps.version_semantic.outputs.version }}
           echo "version is: ${version}"
           if [[ $baseline == 'Y' ]]; then
-            t_current_version=`echo ${version}`
-            echo "t_current_version is: ${t_current_version}"
-            no_sequence=`python3 -c "
-            import semantic_version
-            v = semantic_version.Version('''$ver''')
-            v_major = v.next_major()
-            v_minor = v.next_minor()
-            v_patch = v.next_patch()
-            if('''$t_current_version''' != str(v_major) and '''$t_current_version''' != str(v_minor) and '''$t_current_version''' != str(v_patch)):              
-              print('Y')
-            else:
-              print('N')"`            
-            if [[ $no_sequence != "N" ]]; then
-              echo "Error: Version not in sequential format"
-              exit 1
-            fi
+          t_current_version=`echo ${version}`
+          echo "t_current_version is: ${t_current_version}"
+          no_sequence=`python3 -c "
+          import semantic_version
+          v = semantic_version.Version('''$ver''')
+          v_major = v.next_major()
+          v_minor = v.next_minor()
+          v_patch = v.next_patch()
+          if('''$t_current_version''' != str(v_major) and '''$t_current_version''' != str(v_minor) and '''$t_current_version''' != str(v_patch)):              
+            print('Y')
+          else:
+            print('N')"`            
+          if [[ $no_sequence != "N" ]]; then
+            echo "Error: Version not in sequential format"
+            exit 1
+          fi
           fi
