Test annotated tags 8

diff --git a/.github/workflows/deploy_dev.yml b/.github/workflows/deploy_dev.yml
--- a/.github/workflows/deploy_dev.yml
+++ b/.github/workflows/deploy_dev.yml
@@ -122,20 +122,20 @@ jobs:
       - name: Check if version is in ChangeLog file
         run: |
           version=${{ steps.version_semantic.outputs.version }}
-          echo "version is: ${version}"
-          chgLog=`grep -q "$version" CHANGELOG.md; [ $? -eq 0 ] && echo "Y" || echo "N"`
-          if [[ $chgLog == "N" ]]; then
-            echo "Error: Version not available in CHANGELOG.md file"
+          echo 'version is: ${version}'
+          chgLog=`grep -q '$version' CHANGELOG.md; [ $? -eq 0 ] && echo 'Y' || echo 'N'`
+          if [[ $chgLog == 'N' ]]; then
+            echo 'Error: Version not available in CHANGELOG.md file'
             exit 1
           fi
 
       - name: Check if git tag already exists
         run: |
           version=${{ steps.version_semantic.outputs.version }}
-          echo "version is: ${version}"
+          echo 'version is: ${version}'
           tag=$(git tag -l "$version")
-          if [ ! -z "$tag" ]; then
-            echo "ERROR: Git tag already exists"
+          if [ ! -z '$tag' ]; then
+            echo 'ERROR: Git tag already exists'
             exit 1
           fi
 
@@ -150,7 +150,7 @@ jobs:
             ver=$(git describe --tags `git rev-list --tags --max-count=1`)
           fi
           version=${{ steps.version_semantic.outputs.version }}
-          echo "version is: ${version}"
+          echo 'version is: ${version}'
           if [[ $baseline == 'Y' ]]; then
           t_current_version=`echo ${version}`
           no_sequence=`python3 -c "
@@ -196,6 +196,7 @@ jobs:
 
           git config user.name '$GIT_USER'
           git config user.email '$GIT_MAIL'
-          git tag "$vers" -m 'Tagged by Automated deploy in dev job, Run Number: $GITHUB_RUN_ID'
-          git push origin "$vers"
+          message='Tagged by Automated deploy in dev job, Run Number: $GITHUB_RUN_ID'
+          git tag '$vers' -m '$message'
+          git push origin '$vers'
           echo "git tag '$vers' created"
